### ISSUE TITLE
Revert SSH configuration when uninstalling

### ISSUE THREAD

**Issue by giucal** [KryptCo/kr#86] opened 2017-05-03 16:35 UTC
`kr uninstall` must revert `~/.ssh/config` to its pre-`kr` state.

**Comment by kcking** [comment] 2017-05-03 17:01
Reverting the config is intended behavior but an out-of-date brew formula caused an old uninstallation script to be run. It should be fixed for new brew-based installations (and all other installation methods) now. Thanks for letting us know!

**Closed by kcking** 2017-05-03 17:01 UTC
